name:                aoc2018
version:             0.1.0.0
github:              "ephemient/aoc2018"
license:             BSD3
author:              "Daniel Lin"
maintainer:          "ephemient@gmail.com"
copyright:           "2018 Daniel Lin"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/ephemient/aoc2018#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
  - array
  - containers
  - megaparsec

executables:
  aoc2018-exe:
    main:                Main.lhs
    other-modules:
    - Paths_aoc2018
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -pgmL markdown-unlit
    dependencies:
    - aoc2018
    - markdown-unlit

data-files:
- day*.txt

tests:
  aoc2018-test:
    main:                Main.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc2018
    - hspec

benchmarks:
  aoc2018-bench:
    main:                Main.hs
    source-dirs:         bench
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc2018
    - criterion
